### ISSUE TITLE
user-agent skybellpy/0.6.1... <response [403]>  User is not authorized to access this resource with an explicit deny

### ISSUE THREAD

**Issue by Double-Shindo** [MisterWil/skybellpy#17] opened 2020-08-14 07:08 UTC
I'm lost as to what to do.  I have the latest Skybellpy evidently, but it's been days now since skybell has worked in HA.  I keep reading that others are back to normal after the update 18 days ago.  I'd appreciate any help because I'm stuck.

after running skybellpy with the flags --debug & --device and username and pass the same as they've always been. 

I get several "login successful" messages, but then this error. 

![error](https://user-images.githubusercontent.com/59243947/90222966-bd7a4900-ddd2-11ea-9e7b-dc8f733b0823.png)

**Comment by MisterWil** [comment] 2020-08-14 15:35
I upgraded HASS yesterday (which is usually when I notice issues unless something I use regularly actively stops working) and also ran into this issue. I'm concerned that Skybell is still actively blocking users from accessing its "internal" API even with the changes requested.

Last time @KishCom in a seemingly unofficial capacity let us know what was up. I wonder if he would be willing to chime in again?

**Comment by MisterWil** [comment] 2020-08-14 15:47
Looking at it a little closer, it looks like the login is actually working just fine, as well as a handful of other endpoints. The issue is the endpoint to get the device info `https://cloud.myskybell.com/api/v3/devices/{device}/info` is returning the 403.

**Comment by Double-Shindo** [comment] 2020-08-14 22:21
I appreciate your efforts here man.  Thank you for responding.

**Comment by KishCom** [comment] 2020-08-14 23:53
Nope, no additional blocking or changes that might cause this AFAIK. I'll ask around about that endpoint in particular on Monday.

**Comment by MisterWil** [comment] 2020-08-15 16:59
Looks like it's working again, so it must have just been a random server-side issue that lasted for about 24 hours. Thanks for the reply @KishCom, I really appreciate you being willing to do so. I'm going to go ahead and close this for now.

**Closed as completed by MisterWil** 2020-08-15 16:59 UTC

**Comment by char-mines** [comment] 2021-01-02 05:38
Trying to configure home assistant with my skybell today and im getting [this error](https://pastebin.com/6DmVKvqH) it seems that searching older issues its similar to this error in this issue? Either way is there a possible fix for this or is it skybell's API that is having issues? I would try the debug flag but i'm not exactly sure how to go about that.
